Creating network: templatenet_default
6dad099891fc2bbf5829ac03b60c2fb502361300daa726c4b164c7bf1088858a
NETWORK=templatenet_default \
	GRID_TIMEOUT=30000 \
	SELENIUM_VERSION=3.8.1-dubnium \
	docker-compose -f /Users/varindersingh/Dropbox/Mac_Documents/Workspace/seleniumconf2018/template/docker/grid/docker-compose.yml -p templatenet up -d --scale firefox=1 --scale chrome=1
Creating selenium-hub ... 
[1A[2KCreating selenium-hub ... [32mdone[0m[1BCreating templatenet_chrome_1 ... 
Creating templatenet_firefox_1 ... 
[2A[2KCreating templatenet_chrome_1  ... [32mdone[0m[2B[1A[2KCreating templatenet_firefox_1 ... [32mdone[0m[1B2020-06-13 20:35:06,841 starting /opt/work/tools/systemstat/gridstat
2020-06-13 20:35:06,842 command line options: ['--verbose', '--stdout', '--url', 'http://selenium-hub:4444', '--nodes', '2', '--logfile', '/opt/work/gridstat.log']
2020-06-13 20:35:06,845 checking status of http://selenium-hub:4444
2020-06-13 20:35:06,847 starting at 2020-06-13 20:35:06.847056
2020-06-13 20:35:06,854 ending at 2020-06-13 20:37:06.847056
2020-06-13 20:35:06,929 waiting for hub to respond at http://selenium-hub:4444/grid/api/hub
2020-06-13 20:35:07,937 waiting for hub to respond at http://selenium-hub:4444/grid/api/hub
2020-06-13 20:35:08,945 waiting for hub to respond at http://selenium-hub:4444/grid/api/hub
2020-06-13 20:35:09,958 waiting for hub to respond at http://selenium-hub:4444/grid/api/hub
2020-06-13 20:35:11,424 hub is up at http://selenium-hub:4444/grid/api/hub
2020-06-13 20:35:11,425 0 of 2 nodes are attached
2020-06-13 20:35:11,427 waiting on 2 node(s) to attach
2020-06-13 20:35:12,440 hub is up at http://selenium-hub:4444/grid/api/hub
2020-06-13 20:35:12,442 0 of 2 nodes are attached
2020-06-13 20:35:12,443 waiting on 2 node(s) to attach
2020-06-13 20:35:13,461 hub is up at http://selenium-hub:4444/grid/api/hub
2020-06-13 20:35:13,462 2 of 2 nodes are attached
2020-06-13 20:35:13,463 all nodes are attached
2020-06-13 20:35:13,464 2 of 2 nodes are ready
2020-06-13 20:35:13,465 all nodes are ready
2020-06-13 20:35:13,744 starting /opt/work/tools/systemstat/sutstat
2020-06-13 20:35:13,745 command line options: ['--verbose', '--stdout', '--url', 'http://google.com:80', '--logfile', '/opt/work/sutstat.log']
2020-06-13 20:35:13,746 checking status of http://google.com:80
2020-06-13 20:35:13,747 starting at 2020-06-13 20:35:13.747714
2020-06-13 20:35:13,752 ending at 2020-06-13 20:37:13.747714
2020-06-13 20:35:13,969 System under test is up at http://google.com:80/
rm -f tmp.pipe
mkfifo tmp.pipe
tee selenium_tests.log < tmp.pipe &
docker run --rm --init  --name=tre-`date +'%H%M%S'` --network=templatenet_default --volume=/Users/varindersingh/Dropbox/Mac_Documents/Workspace/seleniumconf2018/template:/opt/work --user=`id -u`:`id -g` --workdir=/opt/work dskard/tew:0.1.0 pytest --junitxml=result.xml --driver=Remote --host=selenium-hub --port=4444 --capability browserName firefox --url=http://google.com:80 --verbose --tb=short --reruns=0 -m "not (fail or systemstat)"  > tmp.pipe || EXITCODE=$?; \
	rm -f tmp.pipe; \
	exit $EXITCODE
============================= test session starts ==============================
platform linux -- Python 3.6.6, pytest-3.6.0, py-1.7.0, pluggy-0.6.0 -- /usr/bin/python3
cachedir: .pytest_cache
driver: Remote
sensitiveurl: .*
metadata: {'Python': '3.6.6', 'Platform': 'Linux-4.19.76-linuxkit-x86_64-with-Ubuntu-18.04-bionic', 'Packages': {'pytest': '3.6.0', 'py': '1.7.0', 'pluggy': '0.6.0'}, 'Plugins': {'xdist': '1.22.2', 'variables': '1.7.1', 'test-groups': '1.0.3', 'selenium': '1.13.0', 'rerunfailures': '4.1', 'repeat': '0.4.1', 'metadata': '1.7.0', 'html': '1.19.0', 'forked': '0.2', 'base-url': '1.4.1'}, 'Base URL': '', 'Driver': 'Remote', 'Capabilities': {'browserName': 'firefox'}, 'Server': 'selenium-hub:4444'}
rootdir: /opt/work, inifile: pytest.ini
plugins: xdist-1.22.2, variables-1.7.1, test-groups-1.0.3, selenium-1.13.0, rerunfailures-4.1, repeat-0.4.1, metadata-1.7.0, html-1.19.0, forked-0.2, base-url-1.4.1
collecting ... collected 9 items / 5 deselected

t/test_front_page_search.py::TestFrontPageSearch::test_search_1 FAILED   [ 25%]
t/test_front_page_search.py::TestFrontPageSearch::test_search_2 FAILED   [ 50%]
t/test_front_page_search.py::TestFrontPageSearch::test_search_3 FAILED   [ 75%]
t/test_front_page_search.py::TestFrontPageSearch::test_search_4 FAILED   [100%]

=================================== FAILURES ===================================
______________________ TestFrontPageSearch.test_search_1 _______________________
/usr/local/lib/python3.6/dist-packages/selene/wait.py:13: in wait_for
    return condition.fn(entity)
/usr/local/lib/python3.6/dist-packages/selene/conditions.py:141: in fn
    return self.match(element.get_actual_webelement())
/usr/local/lib/python3.6/dist-packages/selene/elements.py:205: in get_actual_webelement
    return self.__delegate__
/usr/local/lib/python3.6/dist-packages/selene/elements.py:200: in __delegate__
    return self._locator.find()
/usr/local/lib/python3.6/dist-packages/selene/elements.py:45: in find
    return self._search_context.find_element(*self._by)
/usr/local/lib/python3.6/dist-packages/selene/driver.py:89: in find_element
    return self._webdriver.find_element(by, value)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:955: in find_element
    'value': value})['value']
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:312: in execute
    self.error_handler.check_response(response)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py:242: in check_response
    raise exception_class(message, screen, stacktrace)
E   selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
/usr/local/lib/python3.6/dist-packages/selene/elements.py:188: in _wait_with_screenshot
    return wait_for(entity, condition, timeout, polling)
/usr/local/lib/python3.6/dist-packages/selene/wait.py:35: in wait_for
    reason=reason_string), screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
t/test_front_page_search.py:41: in test_search_1
    .should(be.visible)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:306: in should
    _wait_with_screenshot(self._webdriver, self, condition, timeout)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:193: in _wait_with_screenshot
    raise TimeoutException(msg, e.screen, e.stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats
E               screenshot: file:///opt/work/screen_1592080515784.png
------------------------------- pytest-selenium --------------------------------
URL: https://www.google.com/search?source=hp&ei=jzjlXtTfE9ax0PEPtYeY8A4&q=cheese&oq=cheese&gs_lcp=CgZwc3ktYWIQDDIFCAAQsQMyBQgAELEDMgUIABCxAzIFCAAQsQMyAggAMgIIADICCAAyBQgAELEDMgUIABCxAzIFCAAQsQM6BQgAEIMBUJsRWJUUYMIYaABwAHgAgAG1A4gB7guSAQcyLTEuMS4ymAEAoAEBqgEHZ3dzLXdpeg&sclient=psy-ab&ved=0ahUKEwiU46OS0v_pAhXWGDQIHbUDBu4Q4dUDCAg
______________________ TestFrontPageSearch.test_search_2 _______________________
/usr/local/lib/python3.6/dist-packages/selene/wait.py:13: in wait_for
    return condition.fn(entity)
/usr/local/lib/python3.6/dist-packages/selene/conditions.py:141: in fn
    return self.match(element.get_actual_webelement())
/usr/local/lib/python3.6/dist-packages/selene/elements.py:205: in get_actual_webelement
    return self.__delegate__
/usr/local/lib/python3.6/dist-packages/selene/elements.py:200: in __delegate__
    return self._locator.find()
/usr/local/lib/python3.6/dist-packages/selene/elements.py:45: in find
    return self._search_context.find_element(*self._by)
/usr/local/lib/python3.6/dist-packages/selene/driver.py:89: in find_element
    return self._webdriver.find_element(by, value)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:955: in find_element
    'value': value})['value']
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:312: in execute
    self.error_handler.check_response(response)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py:242: in check_response
    raise exception_class(message, screen, stacktrace)
E   selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
/usr/local/lib/python3.6/dist-packages/selene/elements.py:188: in _wait_with_screenshot
    return wait_for(entity, condition, timeout, polling)
/usr/local/lib/python3.6/dist-packages/selene/wait.py:35: in wait_for
    reason=reason_string), screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
t/test_front_page_search.py:58: in test_search_2
    .should(be.visible)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:306: in should
    _wait_with_screenshot(self._webdriver, self, condition, timeout)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:193: in _wait_with_screenshot
    raise TimeoutException(msg, e.screen, e.stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats
E               screenshot: file:///opt/work/screen_1592080515785.png
------------------------------- pytest-selenium --------------------------------
URL: https://www.google.com/search?source=hp&ei=pzjlXr6NK-jJ0PEPq6-K2AU&q=cheese&oq=cheese&gs_lcp=CgZwc3ktYWIQDDIFCAAQsQMyBQgAELEDMgUIABCxAzIFCAAQsQMyAggAMgIIADICCAAyBQgAELEDMgUIABCxAzIFCAAQsQM6BQgAEIMBULwJWI0NYMgQaABwAHgAgAHuAogBxgqSAQMzLTSYAQCgAQGqAQdnd3Mtd2l6&sclient=psy-ab&ved=0ahUKEwj-_POd0v_pAhXoJDQIHauXAlsQ4dUDCAg
______________________ TestFrontPageSearch.test_search_3 _______________________
/usr/local/lib/python3.6/dist-packages/selene/wait.py:13: in wait_for
    return condition.fn(entity)
/usr/local/lib/python3.6/dist-packages/selene/conditions.py:141: in fn
    return self.match(element.get_actual_webelement())
/usr/local/lib/python3.6/dist-packages/selene/elements.py:205: in get_actual_webelement
    return self.__delegate__
/usr/local/lib/python3.6/dist-packages/selene/elements.py:200: in __delegate__
    return self._locator.find()
/usr/local/lib/python3.6/dist-packages/selene/elements.py:45: in find
    return self._search_context.find_element(*self._by)
/usr/local/lib/python3.6/dist-packages/selene/driver.py:89: in find_element
    return self._webdriver.find_element(by, value)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:955: in find_element
    'value': value})['value']
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:312: in execute
    self.error_handler.check_response(response)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py:242: in check_response
    raise exception_class(message, screen, stacktrace)
E   selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
/usr/local/lib/python3.6/dist-packages/selene/elements.py:188: in _wait_with_screenshot
    return wait_for(entity, condition, timeout, polling)
/usr/local/lib/python3.6/dist-packages/selene/wait.py:35: in wait_for
    reason=reason_string), screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
t/test_front_page_search.py:72: in test_search_3
    .result_stats.should(be.visible)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:306: in should
    _wait_with_screenshot(self._webdriver, self, condition, timeout)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:193: in _wait_with_screenshot
    raise TimeoutException(msg, e.screen, e.stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats
E               screenshot: file:///opt/work/screen_1592080515786.png
------------------------------- pytest-selenium --------------------------------
URL: https://www.google.com/search?source=hp&ei=uzjlXt7bMaK90PEPk4WWsAs&q=cheese&oq=cheese&gs_lcp=CgZwc3ktYWIQDDIFCAAQsQMyBQgAELEDMgUIABCxAzIFCAAQsQMyAggAMgIIADICCAAyBQgAELEDMgUIABCxAzIFCAAQsQM6BQgAEIMBUL4FWK4GYPYIaABwAHgAgAGJAogBwQaSAQUwLjEuM5gBAKABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwiepb-n0v_pAhWiHjQIHZOCBbYQ4dUDCAg
______________________ TestFrontPageSearch.test_search_4 _______________________
/usr/local/lib/python3.6/dist-packages/selene/wait.py:13: in wait_for
    return condition.fn(entity)
/usr/local/lib/python3.6/dist-packages/selene/conditions.py:141: in fn
    return self.match(element.get_actual_webelement())
/usr/local/lib/python3.6/dist-packages/selene/elements.py:205: in get_actual_webelement
    return self.__delegate__
/usr/local/lib/python3.6/dist-packages/selene/elements.py:200: in __delegate__
    return self._locator.find()
/usr/local/lib/python3.6/dist-packages/selene/elements.py:45: in find
    return self._search_context.find_element(*self._by)
/usr/local/lib/python3.6/dist-packages/selene/driver.py:89: in find_element
    return self._webdriver.find_element(by, value)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:955: in find_element
    'value': value})['value']
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:312: in execute
    self.error_handler.check_response(response)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py:242: in check_response
    raise exception_class(message, screen, stacktrace)
E   selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
/usr/local/lib/python3.6/dist-packages/selene/elements.py:188: in _wait_with_screenshot
    return wait_for(entity, condition, timeout, polling)
/usr/local/lib/python3.6/dist-packages/selene/wait.py:35: in wait_for
    reason=reason_string), screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
t/test_front_page_search.py:86: in test_search_4
    .result_stats.should(be.visible)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:306: in should
    _wait_with_screenshot(self._webdriver, self, condition, timeout)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:193: in _wait_with_screenshot
    raise TimeoutException(msg, e.screen, e.stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats
E               screenshot: file:///opt/work/screen_1592080515787.png
------------------------------- pytest-selenium --------------------------------
URL: https://www.google.com/search?source=hp&ei=0zjlXo6pN6Gx0PEP952LsA4&q=cheese&oq=cheese&gs_lcp=CgZwc3ktYWIQDDIFCAAQsQMyBQgAELEDMgUIABCxAzIFCAAQsQMyAggAMgIIADICCAAyBQgAELEDMgUIABCxAzIFCAAQsQM6BQgAEIMBUJAJWNgKYOgMaABwAHgAgAHQAYgBiAaSAQUwLjEuM5gBAKABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwjO3v2y0v_pAhWhGDQIHffOAuYQ4dUDCAg
------------------- generated xml file: /opt/work/result.xml -------------------
=================== 4 failed, 5 deselected in 94.79 seconds ====================
make: *** [test] Error 1
NETWORK=templatenet_default \
	GRID_TIMEOUT=30000 \
	SELENIUM_VERSION=3.8.1-dubnium \
	docker-compose -f /Users/varindersingh/Dropbox/Mac_Documents/Workspace/seleniumconf2018/template/docker/grid/docker-compose.yml -p templatenet down
Stopping templatenet_firefox_1 ... 
Stopping templatenet_chrome_1  ... 
Stopping selenium-hub          ... 
[3A[2KStopping templatenet_firefox_1 ... [32mdone[0m[3B[2A[2KStopping templatenet_chrome_1  ... [32mdone[0m[2B[1A[2KStopping selenium-hub          ... [32mdone[0m[1BRemoving templatenet_firefox_1 ... 
Removing templatenet_chrome_1  ... 
Removing selenium-hub          ... 
[3A[2KRemoving templatenet_firefox_1 ... [32mdone[0m[3B[1A[2KRemoving selenium-hub          ... [32mdone[0m[1B[2A[2KRemoving templatenet_chrome_1  ... [32mdone[0m[2BNetwork templatenet_default is external, skipping
Removing network: templatenet_default
templatenet_default
Creating network: templatenet_default
fa81848290ea020c030545afaf231f67f8facef4f11b939b67c4667c27ff6f9c
NETWORK=templatenet_default \
	GRID_TIMEOUT=30000 \
	SELENIUM_VERSION=3.8.1-dubnium \
	docker-compose -f /Users/varindersingh/Dropbox/Mac_Documents/Workspace/seleniumconf2018/template/docker/grid/docker-compose.yml -p templatenet up -d --scale firefox=1 --scale chrome=1
Creating selenium-hub ... 
[1A[2KCreating selenium-hub ... [32mdone[0m[1BCreating templatenet_firefox_1 ... 
Creating templatenet_chrome_1  ... 
[1A[2KCreating templatenet_chrome_1  ... [32mdone[0m[1B[2A[2KCreating templatenet_firefox_1 ... [32mdone[0m[2B2020-06-13 20:42:06,710 starting /opt/work/tools/systemstat/gridstat
2020-06-13 20:42:06,711 command line options: ['--verbose', '--stdout', '--url', 'http://selenium-hub:4444', '--nodes', '2', '--logfile', '/opt/work/gridstat.log']
2020-06-13 20:42:06,712 checking status of http://selenium-hub:4444
2020-06-13 20:42:06,714 starting at 2020-06-13 20:42:06.714106
2020-06-13 20:42:06,715 ending at 2020-06-13 20:44:06.714106
2020-06-13 20:42:06,734 waiting for hub to respond at http://selenium-hub:4444/grid/api/hub
2020-06-13 20:42:07,739 waiting for hub to respond at http://selenium-hub:4444/grid/api/hub
2020-06-13 20:42:08,748 waiting for hub to respond at http://selenium-hub:4444/grid/api/hub
2020-06-13 20:42:10,185 hub is up at http://selenium-hub:4444/grid/api/hub
2020-06-13 20:42:10,186 0 of 2 nodes are attached
2020-06-13 20:42:10,187 waiting on 2 node(s) to attach
2020-06-13 20:42:11,204 hub is up at http://selenium-hub:4444/grid/api/hub
2020-06-13 20:42:11,205 0 of 2 nodes are attached
2020-06-13 20:42:11,206 waiting on 2 node(s) to attach
2020-06-13 20:42:12,215 hub is up at http://selenium-hub:4444/grid/api/hub
2020-06-13 20:42:12,216 0 of 2 nodes are attached
2020-06-13 20:42:12,217 waiting on 2 node(s) to attach
2020-06-13 20:42:13,227 hub is up at http://selenium-hub:4444/grid/api/hub
2020-06-13 20:42:13,230 2 of 2 nodes are attached
2020-06-13 20:42:13,232 all nodes are attached
2020-06-13 20:42:13,235 2 of 2 nodes are ready
2020-06-13 20:42:13,238 all nodes are ready
2020-06-13 20:42:13,511 starting /opt/work/tools/systemstat/sutstat
2020-06-13 20:42:13,512 command line options: ['--verbose', '--stdout', '--url', 'http://google.com:80', '--logfile', '/opt/work/sutstat.log']
2020-06-13 20:42:13,514 checking status of http://google.com:80
2020-06-13 20:42:13,519 starting at 2020-06-13 20:42:13.518789
2020-06-13 20:42:13,520 ending at 2020-06-13 20:44:13.518789
2020-06-13 20:42:13,813 System under test is up at http://google.com:80/
rm -f tmp.pipe
mkfifo tmp.pipe
tee selenium_tests.log < tmp.pipe &
docker run --rm --init  --name=tre-`date +'%H%M%S'` --network=templatenet_default --volume=/Users/varindersingh/Dropbox/Mac_Documents/Workspace/seleniumconf2018/template:/opt/work --user=`id -u`:`id -g` --workdir=/opt/work dskard/tew:0.1.0 pytest --junitxml=result.xml --driver=Remote --host=selenium-hub --port=4444 --capability browserName firefox --url=http://google.com:80 --verbose --tb=short --reruns=0 -m "not (fail or systemstat)"  > tmp.pipe || EXITCODE=$?; \
	rm -f tmp.pipe; \
	exit $EXITCODE
============================= test session starts ==============================
platform linux -- Python 3.6.6, pytest-3.6.0, py-1.7.0, pluggy-0.6.0 -- /usr/bin/python3
cachedir: .pytest_cache
driver: Remote
sensitiveurl: .*
metadata: {'Python': '3.6.6', 'Platform': 'Linux-4.19.76-linuxkit-x86_64-with-Ubuntu-18.04-bionic', 'Packages': {'pytest': '3.6.0', 'py': '1.7.0', 'pluggy': '0.6.0'}, 'Plugins': {'xdist': '1.22.2', 'variables': '1.7.1', 'test-groups': '1.0.3', 'selenium': '1.13.0', 'rerunfailures': '4.1', 'repeat': '0.4.1', 'metadata': '1.7.0', 'html': '1.19.0', 'forked': '0.2', 'base-url': '1.4.1'}, 'Base URL': '', 'Driver': 'Remote', 'Capabilities': {'browserName': 'firefox'}, 'Server': 'selenium-hub:4444'}
rootdir: /opt/work, inifile: pytest.ini
plugins: xdist-1.22.2, variables-1.7.1, test-groups-1.0.3, selenium-1.13.0, rerunfailures-4.1, repeat-0.4.1, metadata-1.7.0, html-1.19.0, forked-0.2, base-url-1.4.1
collecting ... collected 9 items / 5 deselected

t/test_front_page_search.py::TestFrontPageSearch::test_search_1 FAILED   [ 25%]
t/test_front_page_search.py::TestFrontPageSearch::test_search_2 FAILED   [ 50%]
t/test_front_page_search.py::TestFrontPageSearch::test_search_3 FAILED   [ 75%]
t/test_front_page_search.py::TestFrontPageSearch::test_search_4 FAILED   [100%]

=================================== FAILURES ===================================
______________________ TestFrontPageSearch.test_search_1 _______________________
/usr/local/lib/python3.6/dist-packages/selene/wait.py:13: in wait_for
    return condition.fn(entity)
/usr/local/lib/python3.6/dist-packages/selene/conditions.py:141: in fn
    return self.match(element.get_actual_webelement())
/usr/local/lib/python3.6/dist-packages/selene/elements.py:205: in get_actual_webelement
    return self.__delegate__
/usr/local/lib/python3.6/dist-packages/selene/elements.py:200: in __delegate__
    return self._locator.find()
/usr/local/lib/python3.6/dist-packages/selene/elements.py:45: in find
    return self._search_context.find_element(*self._by)
/usr/local/lib/python3.6/dist-packages/selene/driver.py:89: in find_element
    return self._webdriver.find_element(by, value)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:955: in find_element
    'value': value})['value']
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:312: in execute
    self.error_handler.check_response(response)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py:242: in check_response
    raise exception_class(message, screen, stacktrace)
E   selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
/usr/local/lib/python3.6/dist-packages/selene/elements.py:188: in _wait_with_screenshot
    return wait_for(entity, condition, timeout, polling)
/usr/local/lib/python3.6/dist-packages/selene/wait.py:35: in wait_for
    reason=reason_string), screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
t/test_front_page_search.py:41: in test_search_1
    .should(be.visible)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:306: in should
    _wait_with_screenshot(self._webdriver, self, condition, timeout)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:193: in _wait_with_screenshot
    raise TimeoutException(msg, e.screen, e.stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats
E               screenshot: file:///opt/work/screen_1592080935578.png
------------------------------- pytest-selenium --------------------------------
URL: https://www.google.com/search?source=hp&ei=MTrlXufHCYrNtQaW2oqIBQ&q=cheese&oq=cheese&gs_lcp=CgZwc3ktYWIQDDIFCAAQsQMyBQgAELEDMgUIABCxAzIFCAAQsQMyAggAMgIIADICCAAyBQgAELEDMgUIABCxAzIFCAAQsQM6BQgAEIMBUOQEWKYFYJMIaABwAHgAgAHfAYgB_wWSAQUwLjIuMpgBAKABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwinpMLZ0__pAhWKZs0KHRatAlEQ4dUDCAg
______________________ TestFrontPageSearch.test_search_2 _______________________
/usr/local/lib/python3.6/dist-packages/selene/wait.py:13: in wait_for
    return condition.fn(entity)
/usr/local/lib/python3.6/dist-packages/selene/conditions.py:141: in fn
    return self.match(element.get_actual_webelement())
/usr/local/lib/python3.6/dist-packages/selene/elements.py:205: in get_actual_webelement
    return self.__delegate__
/usr/local/lib/python3.6/dist-packages/selene/elements.py:200: in __delegate__
    return self._locator.find()
/usr/local/lib/python3.6/dist-packages/selene/elements.py:45: in find
    return self._search_context.find_element(*self._by)
/usr/local/lib/python3.6/dist-packages/selene/driver.py:89: in find_element
    return self._webdriver.find_element(by, value)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:955: in find_element
    'value': value})['value']
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:312: in execute
    self.error_handler.check_response(response)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py:242: in check_response
    raise exception_class(message, screen, stacktrace)
E   selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
/usr/local/lib/python3.6/dist-packages/selene/elements.py:188: in _wait_with_screenshot
    return wait_for(entity, condition, timeout, polling)
/usr/local/lib/python3.6/dist-packages/selene/wait.py:35: in wait_for
    reason=reason_string), screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
t/test_front_page_search.py:58: in test_search_2
    .should(be.visible)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:306: in should
    _wait_with_screenshot(self._webdriver, self, condition, timeout)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:193: in _wait_with_screenshot
    raise TimeoutException(msg, e.screen, e.stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats
E               screenshot: file:///opt/work/screen_1592080935579.png
------------------------------- pytest-selenium --------------------------------
URL: https://www.google.com/search?source=hp&ei=QjrlXtnnEomQtAbe64boBg&q=cheese&oq=cheese&gs_lcp=CgZwc3ktYWIQDDIFCAAQsQMyBQgAELEDMgUIABCDATIFCAAQsQMyBQgAELEDMgUIABCxAzICCAAyBQgAELEDMgIIADIFCAAQsQNQyQRYiAVg0gZoAHAAeACAAbQBiAGLApIBAzEuMZgBAKABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwjZkNnh0__pAhUJCM0KHd61AW0Q4dUDCAg
______________________ TestFrontPageSearch.test_search_3 _______________________
/usr/local/lib/python3.6/dist-packages/selene/wait.py:13: in wait_for
    return condition.fn(entity)
/usr/local/lib/python3.6/dist-packages/selene/conditions.py:141: in fn
    return self.match(element.get_actual_webelement())
/usr/local/lib/python3.6/dist-packages/selene/elements.py:205: in get_actual_webelement
    return self.__delegate__
/usr/local/lib/python3.6/dist-packages/selene/elements.py:200: in __delegate__
    return self._locator.find()
/usr/local/lib/python3.6/dist-packages/selene/elements.py:45: in find
    return self._search_context.find_element(*self._by)
/usr/local/lib/python3.6/dist-packages/selene/driver.py:89: in find_element
    return self._webdriver.find_element(by, value)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:955: in find_element
    'value': value})['value']
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:312: in execute
    self.error_handler.check_response(response)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py:242: in check_response
    raise exception_class(message, screen, stacktrace)
E   selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
/usr/local/lib/python3.6/dist-packages/selene/elements.py:188: in _wait_with_screenshot
    return wait_for(entity, condition, timeout, polling)
/usr/local/lib/python3.6/dist-packages/selene/wait.py:35: in wait_for
    reason=reason_string), screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
t/test_front_page_search.py:72: in test_search_3
    .result_stats.should(be.visible)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:306: in should
    _wait_with_screenshot(self._webdriver, self, condition, timeout)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:193: in _wait_with_screenshot
    raise TimeoutException(msg, e.screen, e.stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats
E               screenshot: file:///opt/work/screen_1592080935580.png
------------------------------- pytest-selenium --------------------------------
URL: https://www.google.com/search?source=hp&ei=UjrlXpKNONSQtAa-84iwBg&q=cheese&oq=cheese&gs_lcp=CgZwc3ktYWIQDDIFCAAQsQMyBQgAELEDMgUIABCxAzIFCAAQsQMyAggAMgIIADICCAAyBQgAELEDMgUIABCxAzIFCAAQsQM6BQgAEIMBUIgGWOcGYIAJaABwAHgAgAHqAYgBrwWSAQUwLjIuMpgBAKABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwiS_s7p0__pAhVUCM0KHb45AmYQ4dUDCAg
______________________ TestFrontPageSearch.test_search_4 _______________________
/usr/local/lib/python3.6/dist-packages/selene/wait.py:13: in wait_for
    return condition.fn(entity)
/usr/local/lib/python3.6/dist-packages/selene/conditions.py:141: in fn
    return self.match(element.get_actual_webelement())
/usr/local/lib/python3.6/dist-packages/selene/elements.py:205: in get_actual_webelement
    return self.__delegate__
/usr/local/lib/python3.6/dist-packages/selene/elements.py:200: in __delegate__
    return self._locator.find()
/usr/local/lib/python3.6/dist-packages/selene/elements.py:45: in find
    return self._search_context.find_element(*self._by)
/usr/local/lib/python3.6/dist-packages/selene/driver.py:89: in find_element
    return self._webdriver.find_element(by, value)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:955: in find_element
    'value': value})['value']
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:312: in execute
    self.error_handler.check_response(response)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py:242: in check_response
    raise exception_class(message, screen, stacktrace)
E   selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
/usr/local/lib/python3.6/dist-packages/selene/elements.py:188: in _wait_with_screenshot
    return wait_for(entity, condition, timeout, polling)
/usr/local/lib/python3.6/dist-packages/selene/wait.py:35: in wait_for
    reason=reason_string), screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
t/test_front_page_search.py:86: in test_search_4
    .result_stats.should(be.visible)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:306: in should
    _wait_with_screenshot(self._webdriver, self, condition, timeout)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:193: in _wait_with_screenshot
    raise TimeoutException(msg, e.screen, e.stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats
E               screenshot: file:///opt/work/screen_1592080935581.png
------------------------------- pytest-selenium --------------------------------
URL: https://www.google.com/search?source=hp&ei=bDrlXqOpKL2C9PwPkNWo-Aw&q=cheese&oq=cheese&gs_lcp=CgZwc3ktYWIQDDIFCAAQsQMyBQgAELEDMgUIABCxAzIFCAAQsQMyAggAMgIIADICCAAyBQgAELEDMgUIABCxAzIFCAAQsQM6BQgAEIMBUN4KWLULYLQOaABwAHgAgAHTAogBkgiSAQcwLjEuMS4ymAEAoAEBqgEHZ3dzLXdpeg&sclient=psy-ab&ved=0ahUKEwijj_L10__pAhU9AZ0JHZAqCs8Q4dUDCAg
------------------- generated xml file: /opt/work/result.xml -------------------
=================== 4 failed, 5 deselected in 81.18 seconds ====================
make: *** [test] Error 1
NETWORK=templatenet_default \
	GRID_TIMEOUT=30000 \
	SELENIUM_VERSION=3.8.1-dubnium \
	docker-compose -f /Users/varindersingh/Dropbox/Mac_Documents/Workspace/seleniumconf2018/template/docker/grid/docker-compose.yml -p templatenet down
Stopping templatenet_chrome_1  ... 
Stopping templatenet_firefox_1 ... 
Stopping selenium-hub          ... 
[3A[2KStopping templatenet_chrome_1  ... [32mdone[0m[3B[2A[2KStopping templatenet_firefox_1 ... [32mdone[0m[2B[1A[2KStopping selenium-hub          ... [32mdone[0m[1BRemoving templatenet_chrome_1  ... 
Removing templatenet_firefox_1 ... 
Removing selenium-hub          ... 
[3A[2KRemoving templatenet_chrome_1  ... [32mdone[0m[3B[1A[2KRemoving selenium-hub          ... [32mdone[0m[1B[2A[2KRemoving templatenet_firefox_1 ... [32mdone[0m[2BNetwork templatenet_default is external, skipping
Removing network: templatenet_default
templatenet_default
Creating network: templatenet_default
5130e99d12c94ec5d7ae279179a2f2f8eb12d2daca9ddc00c806ac37dbe3aa54
NETWORK=templatenet_default \
	GRID_TIMEOUT=30000 \
	SELENIUM_VERSION=3.8.1-dubnium \
	docker-compose -f /Users/varindersingh/Dropbox/Mac_Documents/Workspace/seleniumconf2018/template/docker/grid/docker-compose.yml -p templatenet up -d --scale firefox=1 --scale chrome=1
Creating selenium-hub ... 
[1A[2KCreating selenium-hub ... [32mdone[0m[1BCreating templatenet_firefox_1 ... 
Creating templatenet_chrome_1  ... 
[2A[2KCreating templatenet_firefox_1 ... [32mdone[0m[2B[1A[2KCreating templatenet_chrome_1  ... [32mdone[0m[1B2020-06-13 20:49:08,131 starting /opt/work/tools/systemstat/gridstat
2020-06-13 20:49:08,132 command line options: ['--verbose', '--stdout', '--url', 'http://selenium-hub:4444', '--nodes', '2', '--logfile', '/opt/work/gridstat.log']
2020-06-13 20:49:08,135 checking status of http://selenium-hub:4444
2020-06-13 20:49:08,136 starting at 2020-06-13 20:49:08.135833
2020-06-13 20:49:08,136 ending at 2020-06-13 20:51:08.135833
2020-06-13 20:49:08,156 waiting for hub to respond at http://selenium-hub:4444/grid/api/hub
2020-06-13 20:49:09,160 waiting for hub to respond at http://selenium-hub:4444/grid/api/hub
2020-06-13 20:49:10,165 waiting for hub to respond at http://selenium-hub:4444/grid/api/hub
2020-06-13 20:49:11,526 hub is up at http://selenium-hub:4444/grid/api/hub
2020-06-13 20:49:11,527 0 of 2 nodes are attached
2020-06-13 20:49:11,528 waiting on 2 node(s) to attach
2020-06-13 20:49:12,552 hub is up at http://selenium-hub:4444/grid/api/hub
2020-06-13 20:49:12,553 0 of 2 nodes are attached
2020-06-13 20:49:12,554 waiting on 2 node(s) to attach
2020-06-13 20:49:13,571 hub is up at http://selenium-hub:4444/grid/api/hub
2020-06-13 20:49:13,572 0 of 2 nodes are attached
2020-06-13 20:49:13,573 waiting on 2 node(s) to attach
2020-06-13 20:49:14,586 hub is up at http://selenium-hub:4444/grid/api/hub
2020-06-13 20:49:14,586 2 of 2 nodes are attached
2020-06-13 20:49:14,587 all nodes are attached
2020-06-13 20:49:14,588 2 of 2 nodes are ready
2020-06-13 20:49:14,589 all nodes are ready
2020-06-13 20:49:14,899 starting /opt/work/tools/systemstat/sutstat
2020-06-13 20:49:14,900 command line options: ['--verbose', '--stdout', '--url', 'http://google.com:80', '--logfile', '/opt/work/sutstat.log']
2020-06-13 20:49:14,902 checking status of http://google.com:80
2020-06-13 20:49:14,902 starting at 2020-06-13 20:49:14.902846
2020-06-13 20:49:14,903 ending at 2020-06-13 20:51:14.902846
2020-06-13 20:49:15,163 System under test is up at http://google.com:80/
rm -f tmp.pipe
mkfifo tmp.pipe
tee selenium_tests.log < tmp.pipe &
docker run --rm --init  --name=tre-`date +'%H%M%S'` --network=templatenet_default --volume=/Users/varindersingh/Dropbox/Mac_Documents/Workspace/seleniumconf2018/template:/opt/work --user=`id -u`:`id -g` --workdir=/opt/work dskard/tew:0.1.0 pytest --junitxml=result.xml --driver=Remote --host=selenium-hub --port=4444 --capability browserName firefox --url=http://google.com:80 --verbose --tb=short --reruns=0 -m "not (fail or systemstat)"  > tmp.pipe || EXITCODE=$?; \
	rm -f tmp.pipe; \
	exit $EXITCODE
============================= test session starts ==============================
platform linux -- Python 3.6.6, pytest-3.6.0, py-1.7.0, pluggy-0.6.0 -- /usr/bin/python3
cachedir: .pytest_cache
driver: Remote
sensitiveurl: .*
metadata: {'Python': '3.6.6', 'Platform': 'Linux-4.19.76-linuxkit-x86_64-with-Ubuntu-18.04-bionic', 'Packages': {'pytest': '3.6.0', 'py': '1.7.0', 'pluggy': '0.6.0'}, 'Plugins': {'xdist': '1.22.2', 'variables': '1.7.1', 'test-groups': '1.0.3', 'selenium': '1.13.0', 'rerunfailures': '4.1', 'repeat': '0.4.1', 'metadata': '1.7.0', 'html': '1.19.0', 'forked': '0.2', 'base-url': '1.4.1'}, 'Base URL': '', 'Driver': 'Remote', 'Capabilities': {'browserName': 'firefox'}, 'Server': 'selenium-hub:4444'}
rootdir: /opt/work, inifile: pytest.ini
plugins: xdist-1.22.2, variables-1.7.1, test-groups-1.0.3, selenium-1.13.0, rerunfailures-4.1, repeat-0.4.1, metadata-1.7.0, html-1.19.0, forked-0.2, base-url-1.4.1
collecting ... collected 9 items / 5 deselected

t/test_front_page_search.py::TestFrontPageSearch::test_search_1 FAILED   [ 25%]
t/test_front_page_search.py::TestFrontPageSearch::test_search_2 FAILED   [ 50%]
t/test_front_page_search.py::TestFrontPageSearch::test_search_3 FAILED   [ 75%]
t/test_front_page_search.py::TestFrontPageSearch::test_search_4 FAILED   [100%]

=================================== FAILURES ===================================
______________________ TestFrontPageSearch.test_search_1 _______________________
/usr/local/lib/python3.6/dist-packages/selene/wait.py:13: in wait_for
    return condition.fn(entity)
/usr/local/lib/python3.6/dist-packages/selene/conditions.py:141: in fn
    return self.match(element.get_actual_webelement())
/usr/local/lib/python3.6/dist-packages/selene/elements.py:205: in get_actual_webelement
    return self.__delegate__
/usr/local/lib/python3.6/dist-packages/selene/elements.py:200: in __delegate__
    return self._locator.find()
/usr/local/lib/python3.6/dist-packages/selene/elements.py:45: in find
    return self._search_context.find_element(*self._by)
/usr/local/lib/python3.6/dist-packages/selene/driver.py:89: in find_element
    return self._webdriver.find_element(by, value)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:955: in find_element
    'value': value})['value']
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:312: in execute
    self.error_handler.check_response(response)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py:242: in check_response
    raise exception_class(message, screen, stacktrace)
E   selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
/usr/local/lib/python3.6/dist-packages/selene/elements.py:188: in _wait_with_screenshot
    return wait_for(entity, condition, timeout, polling)
/usr/local/lib/python3.6/dist-packages/selene/wait.py:35: in wait_for
    reason=reason_string), screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
t/test_front_page_search.py:41: in test_search_1
    .should(be.visible)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:306: in should
    _wait_with_screenshot(self._webdriver, self, condition, timeout)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:193: in _wait_with_screenshot
    raise TimeoutException(msg, e.screen, e.stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats
E               screenshot: file:///opt/work/screen_1592081357086.png
------------------------------- pytest-selenium --------------------------------
URL: https://www.google.com/search?source=hp&ei=1jvlXpCNHpSC9PwPhL-x4Ak&q=cheese&oq=cheese&gs_lcp=CgZwc3ktYWIQDDIFCAAQsQMyBQgAELEDMgUIABCxAzIFCAAQsQMyAggAMgIIADICCAAyBQgAELEDMgUIABCxAzIFCAAQsQM6BQgAEIMBUNsEWJsFYKgHaABwAHgBgAHuAYgB8wWSAQUwLjIuMpgBAKABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwiQ0Lai1f_pAhUUAZ0JHYRfDJwQ4dUDCAg
______________________ TestFrontPageSearch.test_search_2 _______________________
/usr/local/lib/python3.6/dist-packages/selene/wait.py:13: in wait_for
    return condition.fn(entity)
/usr/local/lib/python3.6/dist-packages/selene/conditions.py:141: in fn
    return self.match(element.get_actual_webelement())
/usr/local/lib/python3.6/dist-packages/selene/elements.py:205: in get_actual_webelement
    return self.__delegate__
/usr/local/lib/python3.6/dist-packages/selene/elements.py:200: in __delegate__
    return self._locator.find()
/usr/local/lib/python3.6/dist-packages/selene/elements.py:45: in find
    return self._search_context.find_element(*self._by)
/usr/local/lib/python3.6/dist-packages/selene/driver.py:89: in find_element
    return self._webdriver.find_element(by, value)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:955: in find_element
    'value': value})['value']
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:312: in execute
    self.error_handler.check_response(response)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py:242: in check_response
    raise exception_class(message, screen, stacktrace)
E   selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
/usr/local/lib/python3.6/dist-packages/selene/elements.py:188: in _wait_with_screenshot
    return wait_for(entity, condition, timeout, polling)
/usr/local/lib/python3.6/dist-packages/selene/wait.py:35: in wait_for
    reason=reason_string), screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
t/test_front_page_search.py:58: in test_search_2
    .should(be.visible)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:306: in should
    _wait_with_screenshot(self._webdriver, self, condition, timeout)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:193: in _wait_with_screenshot
    raise TimeoutException(msg, e.screen, e.stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats
E               screenshot: file:///opt/work/screen_1592081357087.png
------------------------------- pytest-selenium --------------------------------
URL: https://www.google.com/search?source=hp&ei=9DvlXrDREIjbtAb0orfABg&q=cheese&oq=cheese&gs_lcp=CgZwc3ktYWIQDDIFCAAQsQMyBQgAELEDMgUIABCxAzIFCAAQsQMyAggAMgIIADICCAAyBQgAELEDMgUIABCxAzIFCAAQsQM6BQgAEIMBUN8HWMsIYLALaABwAHgAgAGQAogBxgaSAQUwLjEuM5gBAKABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwiwm9Cw1f_pAhWILc0KHXTRDWgQ4dUDCAg
______________________ TestFrontPageSearch.test_search_3 _______________________
/usr/local/lib/python3.6/dist-packages/selene/wait.py:13: in wait_for
    return condition.fn(entity)
/usr/local/lib/python3.6/dist-packages/selene/conditions.py:141: in fn
    return self.match(element.get_actual_webelement())
/usr/local/lib/python3.6/dist-packages/selene/elements.py:205: in get_actual_webelement
    return self.__delegate__
/usr/local/lib/python3.6/dist-packages/selene/elements.py:200: in __delegate__
    return self._locator.find()
/usr/local/lib/python3.6/dist-packages/selene/elements.py:45: in find
    return self._search_context.find_element(*self._by)
/usr/local/lib/python3.6/dist-packages/selene/driver.py:89: in find_element
    return self._webdriver.find_element(by, value)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:955: in find_element
    'value': value})['value']
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:312: in execute
    self.error_handler.check_response(response)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py:242: in check_response
    raise exception_class(message, screen, stacktrace)
E   selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
/usr/local/lib/python3.6/dist-packages/selene/elements.py:188: in _wait_with_screenshot
    return wait_for(entity, condition, timeout, polling)
/usr/local/lib/python3.6/dist-packages/selene/wait.py:35: in wait_for
    reason=reason_string), screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
t/test_front_page_search.py:72: in test_search_3
    .result_stats.should(be.visible)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:306: in should
    _wait_with_screenshot(self._webdriver, self, condition, timeout)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:193: in _wait_with_screenshot
    raise TimeoutException(msg, e.screen, e.stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats
E               screenshot: file:///opt/work/screen_1592081357088.png
------------------------------- pytest-selenium --------------------------------
URL: https://www.google.com/search?source=hp&ei=CDzlXtPyOpK3tAal-43IDA&q=cheese&oq=cheese&gs_lcp=CgZwc3ktYWIQDDIFCAAQsQMyBQgAELEDMgUIABCxAzIFCAAQsQMyAggAMgIIADICCAAyBQgAELEDMgUIABCxAzIFCAAQsQM6BQgAEIMBUIYCWOoCYIoFaABwAHgAgAH_AYgBxwaSAQUwLjEuM5gBAKABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwjTlr-61f_pAhWSG80KHaV9A8kQ4dUDCAg
______________________ TestFrontPageSearch.test_search_4 _______________________
/usr/local/lib/python3.6/dist-packages/selene/wait.py:13: in wait_for
    return condition.fn(entity)
/usr/local/lib/python3.6/dist-packages/selene/conditions.py:141: in fn
    return self.match(element.get_actual_webelement())
/usr/local/lib/python3.6/dist-packages/selene/elements.py:205: in get_actual_webelement
    return self.__delegate__
/usr/local/lib/python3.6/dist-packages/selene/elements.py:200: in __delegate__
    return self._locator.find()
/usr/local/lib/python3.6/dist-packages/selene/elements.py:45: in find
    return self._search_context.find_element(*self._by)
/usr/local/lib/python3.6/dist-packages/selene/driver.py:89: in find_element
    return self._webdriver.find_element(by, value)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:955: in find_element
    'value': value})['value']
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:312: in execute
    self.error_handler.check_response(response)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py:242: in check_response
    raise exception_class(message, screen, stacktrace)
E   selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
/usr/local/lib/python3.6/dist-packages/selene/elements.py:188: in _wait_with_screenshot
    return wait_for(entity, condition, timeout, polling)
/usr/local/lib/python3.6/dist-packages/selene/wait.py:35: in wait_for
    reason=reason_string), screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
t/test_front_page_search.py:86: in test_search_4
    .result_stats.should(be.visible)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:306: in should
    _wait_with_screenshot(self._webdriver, self, condition, timeout)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:193: in _wait_with_screenshot
    raise TimeoutException(msg, e.screen, e.stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats
E               screenshot: file:///opt/work/screen_1592081357089.png
------------------------------- pytest-selenium --------------------------------
URL: https://www.google.com/search?source=hp&ei=GTzlXq7lLNW8tAae54mwBA&q=cheese&oq=cheese&gs_lcp=CgZwc3ktYWIQDDIFCAAQsQMyBQgAELEDMgUIABCxAzIFCAAQsQMyAggAMgIIADICCAAyBQgAELEDMgUIABCxAzIFCAAQsQM6BQgAEIMBUIMEWMUEYJEGaABwAHgAgAGvAYgBwgSSAQMxLjOYAQCgAQGqAQdnd3Mtd2l6&sclient=psy-ab&ved=0ahUKEwju1b7C1f_pAhVVHs0KHZ5zAkYQ4dUDCAg
------------------- generated xml file: /opt/work/result.xml -------------------
=================== 4 failed, 5 deselected in 85.99 seconds ====================
make: *** [test] Error 1
NETWORK=templatenet_default \
	GRID_TIMEOUT=30000 \
	SELENIUM_VERSION=3.8.1-dubnium \
	docker-compose -f /Users/varindersingh/Dropbox/Mac_Documents/Workspace/seleniumconf2018/template/docker/grid/docker-compose.yml -p templatenet down
Stopping templatenet_firefox_1 ... 
Stopping templatenet_chrome_1  ... 
Stopping selenium-hub          ... 
[2A[2KStopping templatenet_chrome_1  ... [32mdone[0m[2B[3A[2KStopping templatenet_firefox_1 ... [32mdone[0m[3B[1A[2KStopping selenium-hub          ... [32mdone[0m[1BRemoving templatenet_firefox_1 ... 
Removing templatenet_chrome_1  ... 
Removing selenium-hub          ... 
[2A[2KRemoving templatenet_chrome_1  ... [32mdone[0m[2B[1A[2KRemoving selenium-hub          ... [32mdone[0m[1B[3A[2KRemoving templatenet_firefox_1 ... [32mdone[0m[3BNetwork templatenet_default is external, skipping
Removing network: templatenet_default
templatenet_default
Creating network: templatenet_default
a3b3bfbd5f354da554bdb2f5fb2a1932576fbbeb98ee7766ef4c63a6ad3dbb10
NETWORK=templatenet_default \
	GRID_TIMEOUT=30000 \
	SELENIUM_VERSION=3.8.1-dubnium \
	docker-compose -f /Users/varindersingh/Dropbox/Mac_Documents/Workspace/seleniumconf2018/template/docker/grid/docker-compose.yml -p templatenet up -d --scale firefox=1 --scale chrome=1
Creating selenium-hub ... 
[1A[2KCreating selenium-hub ... [32mdone[0m[1BCreating templatenet_firefox_1 ... 
Creating templatenet_chrome_1  ... 
[2A[2KCreating templatenet_firefox_1 ... [32mdone[0m[2B[1A[2KCreating templatenet_chrome_1  ... [32mdone[0m[1B2020-06-13 20:56:06,847 starting /opt/work/tools/systemstat/gridstat
2020-06-13 20:56:06,848 command line options: ['--verbose', '--stdout', '--url', 'http://selenium-hub:4444', '--nodes', '2', '--logfile', '/opt/work/gridstat.log']
2020-06-13 20:56:06,849 checking status of http://selenium-hub:4444
2020-06-13 20:56:06,851 starting at 2020-06-13 20:56:06.850637
2020-06-13 20:56:06,854 ending at 2020-06-13 20:58:06.850637
2020-06-13 20:56:06,870 waiting for hub to respond at http://selenium-hub:4444/grid/api/hub
2020-06-13 20:56:07,877 waiting for hub to respond at http://selenium-hub:4444/grid/api/hub
2020-06-13 20:56:08,883 waiting for hub to respond at http://selenium-hub:4444/grid/api/hub
2020-06-13 20:56:10,175 hub is up at http://selenium-hub:4444/grid/api/hub
2020-06-13 20:56:10,176 0 of 2 nodes are attached
2020-06-13 20:56:10,177 waiting on 2 node(s) to attach
2020-06-13 20:56:11,198 hub is up at http://selenium-hub:4444/grid/api/hub
2020-06-13 20:56:11,199 0 of 2 nodes are attached
2020-06-13 20:56:11,200 waiting on 2 node(s) to attach
2020-06-13 20:56:12,217 hub is up at http://selenium-hub:4444/grid/api/hub
2020-06-13 20:56:12,218 0 of 2 nodes are attached
2020-06-13 20:56:12,220 waiting on 2 node(s) to attach
2020-06-13 20:56:13,232 hub is up at http://selenium-hub:4444/grid/api/hub
2020-06-13 20:56:13,239 2 of 2 nodes are attached
2020-06-13 20:56:13,240 all nodes are attached
2020-06-13 20:56:13,241 2 of 2 nodes are ready
2020-06-13 20:56:13,242 all nodes are ready
2020-06-13 20:56:13,536 starting /opt/work/tools/systemstat/sutstat
2020-06-13 20:56:13,538 command line options: ['--verbose', '--stdout', '--url', 'http://google.com:80', '--logfile', '/opt/work/sutstat.log']
2020-06-13 20:56:13,539 checking status of http://google.com:80
2020-06-13 20:56:13,540 starting at 2020-06-13 20:56:13.540296
2020-06-13 20:56:13,541 ending at 2020-06-13 20:58:13.540296
2020-06-13 20:56:13,836 System under test is up at http://google.com:80/
rm -f tmp.pipe
mkfifo tmp.pipe
tee selenium_tests.log < tmp.pipe &
docker run --rm --init  --name=tre-`date +'%H%M%S'` --network=templatenet_default --volume=/Users/varindersingh/Dropbox/Mac_Documents/Workspace/seleniumconf2018/template:/opt/work --user=`id -u`:`id -g` --workdir=/opt/work dskard/tew:0.1.0 pytest --junitxml=result.xml --driver=Remote --host=selenium-hub --port=4444 --capability browserName firefox --url=http://google.com:80 --verbose --tb=short --reruns=0 -m "not (fail or systemstat)"  > tmp.pipe || EXITCODE=$?; \
	rm -f tmp.pipe; \
	exit $EXITCODE
============================= test session starts ==============================
platform linux -- Python 3.6.6, pytest-3.6.0, py-1.7.0, pluggy-0.6.0 -- /usr/bin/python3
cachedir: .pytest_cache
driver: Remote
sensitiveurl: .*
metadata: {'Python': '3.6.6', 'Platform': 'Linux-4.19.76-linuxkit-x86_64-with-Ubuntu-18.04-bionic', 'Packages': {'pytest': '3.6.0', 'py': '1.7.0', 'pluggy': '0.6.0'}, 'Plugins': {'xdist': '1.22.2', 'variables': '1.7.1', 'test-groups': '1.0.3', 'selenium': '1.13.0', 'rerunfailures': '4.1', 'repeat': '0.4.1', 'metadata': '1.7.0', 'html': '1.19.0', 'forked': '0.2', 'base-url': '1.4.1'}, 'Base URL': '', 'Driver': 'Remote', 'Capabilities': {'browserName': 'firefox'}, 'Server': 'selenium-hub:4444'}
rootdir: /opt/work, inifile: pytest.ini
plugins: xdist-1.22.2, variables-1.7.1, test-groups-1.0.3, selenium-1.13.0, rerunfailures-4.1, repeat-0.4.1, metadata-1.7.0, html-1.19.0, forked-0.2, base-url-1.4.1
collecting ... collected 9 items / 5 deselected

t/test_front_page_search.py::TestFrontPageSearch::test_search_1 FAILED   [ 25%]
t/test_front_page_search.py::TestFrontPageSearch::test_search_2 FAILED   [ 50%]
t/test_front_page_search.py::TestFrontPageSearch::test_search_3 FAILED   [ 75%]
t/test_front_page_search.py::TestFrontPageSearch::test_search_4 FAILED   [100%]

=================================== FAILURES ===================================
______________________ TestFrontPageSearch.test_search_1 _______________________
/usr/local/lib/python3.6/dist-packages/selene/wait.py:13: in wait_for
    return condition.fn(entity)
/usr/local/lib/python3.6/dist-packages/selene/conditions.py:141: in fn
    return self.match(element.get_actual_webelement())
/usr/local/lib/python3.6/dist-packages/selene/elements.py:205: in get_actual_webelement
    return self.__delegate__
/usr/local/lib/python3.6/dist-packages/selene/elements.py:200: in __delegate__
    return self._locator.find()
/usr/local/lib/python3.6/dist-packages/selene/elements.py:45: in find
    return self._search_context.find_element(*self._by)
/usr/local/lib/python3.6/dist-packages/selene/driver.py:89: in find_element
    return self._webdriver.find_element(by, value)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:955: in find_element
    'value': value})['value']
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:312: in execute
    self.error_handler.check_response(response)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py:242: in check_response
    raise exception_class(message, screen, stacktrace)
E   selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
/usr/local/lib/python3.6/dist-packages/selene/elements.py:188: in _wait_with_screenshot
    return wait_for(entity, condition, timeout, polling)
/usr/local/lib/python3.6/dist-packages/selene/wait.py:35: in wait_for
    reason=reason_string), screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
t/test_front_page_search.py:41: in test_search_1
    .should(be.visible)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:306: in should
    _wait_with_screenshot(self._webdriver, self, condition, timeout)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:193: in _wait_with_screenshot
    raise TimeoutException(msg, e.screen, e.stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats
E               screenshot: file:///opt/work/screen_1592081776004.png
------------------------------- pytest-selenium --------------------------------
URL: https://www.google.com/search?source=hp&ei=eT3lXqPxOIKttQbf55ioCg&q=cheese&oq=cheese&gs_lcp=CgZwc3ktYWIQDDIFCAAQsQMyBQgAELEDMgUIABCxAzIFCAAQsQMyAggAMgIIADICCAAyBQgAELEDMgUIABCxAzIFCAAQsQM6BQgAEIMBUOQCWKgDYMEGaABwAHgAgAGVAogBnAaSAQUwLjIuMpgBAKABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwjjkbfq1v_pAhWCVs0KHd8zBqUQ4dUDCAg
______________________ TestFrontPageSearch.test_search_2 _______________________
/usr/local/lib/python3.6/dist-packages/selene/wait.py:13: in wait_for
    return condition.fn(entity)
/usr/local/lib/python3.6/dist-packages/selene/conditions.py:141: in fn
    return self.match(element.get_actual_webelement())
/usr/local/lib/python3.6/dist-packages/selene/elements.py:205: in get_actual_webelement
    return self.__delegate__
/usr/local/lib/python3.6/dist-packages/selene/elements.py:200: in __delegate__
    return self._locator.find()
/usr/local/lib/python3.6/dist-packages/selene/elements.py:45: in find
    return self._search_context.find_element(*self._by)
/usr/local/lib/python3.6/dist-packages/selene/driver.py:89: in find_element
    return self._webdriver.find_element(by, value)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:955: in find_element
    'value': value})['value']
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:312: in execute
    self.error_handler.check_response(response)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py:242: in check_response
    raise exception_class(message, screen, stacktrace)
E   selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
/usr/local/lib/python3.6/dist-packages/selene/elements.py:188: in _wait_with_screenshot
    return wait_for(entity, condition, timeout, polling)
/usr/local/lib/python3.6/dist-packages/selene/wait.py:35: in wait_for
    reason=reason_string), screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
t/test_front_page_search.py:58: in test_search_2
    .should(be.visible)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:306: in should
    _wait_with_screenshot(self._webdriver, self, condition, timeout)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:193: in _wait_with_screenshot
    raise TimeoutException(msg, e.screen, e.stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats
E               screenshot: file:///opt/work/screen_1592081776005.png
------------------------------- pytest-selenium --------------------------------
URL: https://www.google.com/search?source=hp&ei=iz3lXuyNIJC7tQb-vIKYAg&q=cheese&oq=cheese&gs_lcp=CgZwc3ktYWIQDDIFCAAQsQMyBQgAELEDMgUIABCxAzIFCAAQsQMyAggAMgIIADICCAAyBQgAELEDMgUIABCxAzIFCAAQsQM6BQgAEIMBUIEGWIcHYOcJaABwAHgAgAH-AYgB8waSAQUwLjEuM5gBAKABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwis_-jy1v_pAhWQXc0KHX6eACMQ4dUDCAg
______________________ TestFrontPageSearch.test_search_3 _______________________
/usr/local/lib/python3.6/dist-packages/selene/wait.py:13: in wait_for
    return condition.fn(entity)
/usr/local/lib/python3.6/dist-packages/selene/conditions.py:141: in fn
    return self.match(element.get_actual_webelement())
/usr/local/lib/python3.6/dist-packages/selene/elements.py:205: in get_actual_webelement
    return self.__delegate__
/usr/local/lib/python3.6/dist-packages/selene/elements.py:200: in __delegate__
    return self._locator.find()
/usr/local/lib/python3.6/dist-packages/selene/elements.py:45: in find
    return self._search_context.find_element(*self._by)
/usr/local/lib/python3.6/dist-packages/selene/driver.py:89: in find_element
    return self._webdriver.find_element(by, value)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:955: in find_element
    'value': value})['value']
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:312: in execute
    self.error_handler.check_response(response)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py:242: in check_response
    raise exception_class(message, screen, stacktrace)
E   selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
/usr/local/lib/python3.6/dist-packages/selene/elements.py:188: in _wait_with_screenshot
    return wait_for(entity, condition, timeout, polling)
/usr/local/lib/python3.6/dist-packages/selene/wait.py:35: in wait_for
    reason=reason_string), screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
t/test_front_page_search.py:72: in test_search_3
    .result_stats.should(be.visible)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:306: in should
    _wait_with_screenshot(self._webdriver, self, condition, timeout)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:193: in _wait_with_screenshot
    raise TimeoutException(msg, e.screen, e.stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats
E               screenshot: file:///opt/work/screen_1592081776006.png
------------------------------- pytest-selenium --------------------------------
URL: https://www.google.com/search?source=hp&ei=oT3lXr-QIdG6tAaR8pfQDA&q=cheese&oq=cheese&gs_lcp=CgZwc3ktYWIQDDIFCAAQsQMyBQgAELEDMgUIABCxAzIFCAAQsQMyAggAMgIIADICCAAyBQgAELEDMgUIABCxAzIFCAAQsQM6BQgAEIMBUPYJWI4NYK4PaABwAHgAgAHdAYgBtgaSAQUwLjEuM5gBAKABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwj_5Kj91v_pAhVRHc0KHRH5BcoQ4dUDCAg
______________________ TestFrontPageSearch.test_search_4 _______________________
/usr/local/lib/python3.6/dist-packages/selene/wait.py:13: in wait_for
    return condition.fn(entity)
/usr/local/lib/python3.6/dist-packages/selene/conditions.py:141: in fn
    return self.match(element.get_actual_webelement())
/usr/local/lib/python3.6/dist-packages/selene/elements.py:205: in get_actual_webelement
    return self.__delegate__
/usr/local/lib/python3.6/dist-packages/selene/elements.py:200: in __delegate__
    return self._locator.find()
/usr/local/lib/python3.6/dist-packages/selene/elements.py:45: in find
    return self._search_context.find_element(*self._by)
/usr/local/lib/python3.6/dist-packages/selene/driver.py:89: in find_element
    return self._webdriver.find_element(by, value)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:955: in find_element
    'value': value})['value']
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:312: in execute
    self.error_handler.check_response(response)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py:242: in check_response
    raise exception_class(message, screen, stacktrace)
E   selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
/usr/local/lib/python3.6/dist-packages/selene/elements.py:188: in _wait_with_screenshot
    return wait_for(entity, condition, timeout, polling)
/usr/local/lib/python3.6/dist-packages/selene/wait.py:35: in wait_for
    reason=reason_string), screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
t/test_front_page_search.py:86: in test_search_4
    .result_stats.should(be.visible)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:306: in should
    _wait_with_screenshot(self._webdriver, self, condition, timeout)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:193: in _wait_with_screenshot
    raise TimeoutException(msg, e.screen, e.stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats
E               screenshot: file:///opt/work/screen_1592081776007.png
------------------------------- pytest-selenium --------------------------------
URL: https://www.google.com/search?source=hp&ei=sj3lXqe2NNe4tAaez7v4AQ&q=cheese&oq=cheese&gs_lcp=CgZwc3ktYWIQDDIFCAAQsQMyBQgAELEDMgUIABCxAzIFCAAQsQMyAggAMgIIADICCAAyBQgAELEDMgUIABCxAzIFCAAQsQM6BQgAEIMBUOMFWLcGYKcIaABwAHgAgAHLAYgBtgWSAQUwLjMuMZgBAKABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwin18mF1__pAhVXHM0KHZ7nDh8Q4dUDCAg
------------------- generated xml file: /opt/work/result.xml -------------------
=================== 4 failed, 5 deselected in 79.27 seconds ====================
make: *** [test] Error 1
NETWORK=templatenet_default \
	GRID_TIMEOUT=30000 \
	SELENIUM_VERSION=3.8.1-dubnium \
	docker-compose -f /Users/varindersingh/Dropbox/Mac_Documents/Workspace/seleniumconf2018/template/docker/grid/docker-compose.yml -p templatenet down
Stopping templatenet_chrome_1  ... 
Stopping templatenet_firefox_1 ... 
Stopping selenium-hub          ... 
[3A[2KStopping templatenet_chrome_1  ... [32mdone[0m[3B[2A[2KStopping templatenet_firefox_1 ... [32mdone[0m[2B[1A[2KStopping selenium-hub          ... [32mdone[0m[1BRemoving templatenet_chrome_1  ... 
Removing templatenet_firefox_1 ... 
Removing selenium-hub          ... 
[1A[2KRemoving selenium-hub          ... [32mdone[0m[1B[3A[2KRemoving templatenet_chrome_1  ... [32mdone[0m[3B[2A[2KRemoving templatenet_firefox_1 ... [32mdone[0m[2BNetwork templatenet_default is external, skipping
Removing network: templatenet_default
templatenet_default
Creating network: templatenet_default
00ae19b40855f058d673a958ac37d2e55df89520fc68c1fc53612a33631ffa4c
NETWORK=templatenet_default \
	GRID_TIMEOUT=30000 \
	SELENIUM_VERSION=3.8.1-dubnium \
	docker-compose -f /Users/varindersingh/Dropbox/Mac_Documents/Workspace/seleniumconf2018/template/docker/grid/docker-compose.yml -p templatenet up -d --scale firefox=1 --scale chrome=1
Creating selenium-hub ... 
[1A[2KCreating selenium-hub ... [32mdone[0m[1BCreating templatenet_firefox_1 ... 
Creating templatenet_chrome_1  ... 
[2A[2KCreating templatenet_firefox_1 ... [32mdone[0m[2B[1A[2KCreating templatenet_chrome_1  ... [32mdone[0m[1B2020-06-13 21:00:07,525 starting /opt/work/tools/systemstat/gridstat
2020-06-13 21:00:07,526 command line options: ['--verbose', '--stdout', '--url', 'http://selenium-hub:4444', '--nodes', '2', '--logfile', '/opt/work/gridstat.log']
2020-06-13 21:00:07,527 checking status of http://selenium-hub:4444
2020-06-13 21:00:07,528 starting at 2020-06-13 21:00:07.527808
2020-06-13 21:00:07,528 ending at 2020-06-13 21:02:07.527808
2020-06-13 21:00:07,540 waiting for hub to respond at http://selenium-hub:4444/grid/api/hub
2020-06-13 21:00:08,548 waiting for hub to respond at http://selenium-hub:4444/grid/api/hub
2020-06-13 21:00:09,557 waiting for hub to respond at http://selenium-hub:4444/grid/api/hub
2020-06-13 21:00:10,562 waiting for hub to respond at http://selenium-hub:4444/grid/api/hub
2020-06-13 21:00:11,566 waiting for hub to respond at http://selenium-hub:4444/grid/api/hub
2020-06-13 21:00:12,886 hub is up at http://selenium-hub:4444/grid/api/hub
2020-06-13 21:00:12,887 0 of 2 nodes are attached
2020-06-13 21:00:12,888 waiting on 2 node(s) to attach
2020-06-13 21:00:13,916 hub is up at http://selenium-hub:4444/grid/api/hub
2020-06-13 21:00:13,916 0 of 2 nodes are attached
2020-06-13 21:00:13,917 waiting on 2 node(s) to attach
2020-06-13 21:00:14,907 hub is up at http://selenium-hub:4444/grid/api/hub
2020-06-13 21:00:14,908 2 of 2 nodes are attached
2020-06-13 21:00:14,909 all nodes are attached
2020-06-13 21:00:14,910 2 of 2 nodes are ready
2020-06-13 21:00:14,911 all nodes are ready
2020-06-13 21:00:15,168 starting /opt/work/tools/systemstat/sutstat
2020-06-13 21:00:15,169 command line options: ['--verbose', '--stdout', '--url', 'http://google.com:80', '--logfile', '/opt/work/sutstat.log']
2020-06-13 21:00:15,170 checking status of http://google.com:80
2020-06-13 21:00:15,171 starting at 2020-06-13 21:00:15.171501
2020-06-13 21:00:15,172 ending at 2020-06-13 21:02:15.171501
2020-06-13 21:00:15,396 System under test is up at http://google.com:80/
rm -f tmp.pipe
mkfifo tmp.pipe
tee selenium_tests.log < tmp.pipe &
docker run --rm --init  --name=tre-`date +'%H%M%S'` --network=templatenet_default --volume=/Users/varindersingh/Dropbox/Mac_Documents/Workspace/seleniumconf2018/template:/opt/work --user=`id -u`:`id -g` --workdir=/opt/work dskard/tew:0.1.0 pytest --junitxml=result.xml --driver=Remote --host=selenium-hub --port=4444 --capability browserName firefox --url=http://google.com:80 --verbose --tb=short --reruns=0 -m "not (fail or systemstat)"  > tmp.pipe || EXITCODE=$?; \
	rm -f tmp.pipe; \
	exit $EXITCODE
============================= test session starts ==============================
platform linux -- Python 3.6.6, pytest-3.6.0, py-1.7.0, pluggy-0.6.0 -- /usr/bin/python3
cachedir: .pytest_cache
driver: Remote
sensitiveurl: .*
metadata: {'Python': '3.6.6', 'Platform': 'Linux-4.19.76-linuxkit-x86_64-with-Ubuntu-18.04-bionic', 'Packages': {'pytest': '3.6.0', 'py': '1.7.0', 'pluggy': '0.6.0'}, 'Plugins': {'xdist': '1.22.2', 'variables': '1.7.1', 'test-groups': '1.0.3', 'selenium': '1.13.0', 'rerunfailures': '4.1', 'repeat': '0.4.1', 'metadata': '1.7.0', 'html': '1.19.0', 'forked': '0.2', 'base-url': '1.4.1'}, 'Base URL': '', 'Driver': 'Remote', 'Capabilities': {'browserName': 'firefox'}, 'Server': 'selenium-hub:4444'}
rootdir: /opt/work, inifile: pytest.ini
plugins: xdist-1.22.2, variables-1.7.1, test-groups-1.0.3, selenium-1.13.0, rerunfailures-4.1, repeat-0.4.1, metadata-1.7.0, html-1.19.0, forked-0.2, base-url-1.4.1
collecting ... collected 9 items / 5 deselected

t/test_front_page_search.py::TestFrontPageSearch::test_search_1 FAILED   [ 25%]
t/test_front_page_search.py::TestFrontPageSearch::test_search_2 FAILED   [ 50%]
t/test_front_page_search.py::TestFrontPageSearch::test_search_3 FAILED   [ 75%]
t/test_front_page_search.py::TestFrontPageSearch::test_search_4 FAILED   [100%]

=================================== FAILURES ===================================
______________________ TestFrontPageSearch.test_search_1 _______________________
/usr/local/lib/python3.6/dist-packages/selene/wait.py:13: in wait_for
    return condition.fn(entity)
/usr/local/lib/python3.6/dist-packages/selene/conditions.py:141: in fn
    return self.match(element.get_actual_webelement())
/usr/local/lib/python3.6/dist-packages/selene/elements.py:205: in get_actual_webelement
    return self.__delegate__
/usr/local/lib/python3.6/dist-packages/selene/elements.py:200: in __delegate__
    return self._locator.find()
/usr/local/lib/python3.6/dist-packages/selene/elements.py:45: in find
    return self._search_context.find_element(*self._by)
/usr/local/lib/python3.6/dist-packages/selene/driver.py:89: in find_element
    return self._webdriver.find_element(by, value)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:955: in find_element
    'value': value})['value']
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:312: in execute
    self.error_handler.check_response(response)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py:242: in check_response
    raise exception_class(message, screen, stacktrace)
E   selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
/usr/local/lib/python3.6/dist-packages/selene/elements.py:188: in _wait_with_screenshot
    return wait_for(entity, condition, timeout, polling)
/usr/local/lib/python3.6/dist-packages/selene/wait.py:35: in wait_for
    reason=reason_string), screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
t/test_front_page_search.py:41: in test_search_1
    .should(be.visible)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:306: in should
    _wait_with_screenshot(self._webdriver, self, condition, timeout)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:193: in _wait_with_screenshot
    raise TimeoutException(msg, e.screen, e.stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats
E               screenshot: file:///opt/work/screen_1592082017309.png
------------------------------- pytest-selenium --------------------------------
URL: https://www.google.com/search?source=hp&ei=az7lXpiGBZWMtAa0h4DABg&q=cheese&oq=cheese&gs_lcp=CgZwc3ktYWIQDDIFCAAQsQMyBQgAELEDMgUIABCxAzIFCAAQsQMyAggAMgIIADICCAAyBQgAELEDMgUIABCxAzIFCAAQsQM6BQgAEIMBUM8EWIsFYKAHaABwAHgBgAHeAYgBngWSAQUwLjMuMZgBAKABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwjY57Xd1__pAhUVBs0KHbQDAGgQ4dUDCAg
______________________ TestFrontPageSearch.test_search_2 _______________________
/usr/local/lib/python3.6/dist-packages/selene/wait.py:13: in wait_for
    return condition.fn(entity)
/usr/local/lib/python3.6/dist-packages/selene/conditions.py:141: in fn
    return self.match(element.get_actual_webelement())
/usr/local/lib/python3.6/dist-packages/selene/elements.py:205: in get_actual_webelement
    return self.__delegate__
/usr/local/lib/python3.6/dist-packages/selene/elements.py:200: in __delegate__
    return self._locator.find()
/usr/local/lib/python3.6/dist-packages/selene/elements.py:45: in find
    return self._search_context.find_element(*self._by)
/usr/local/lib/python3.6/dist-packages/selene/driver.py:89: in find_element
    return self._webdriver.find_element(by, value)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:955: in find_element
    'value': value})['value']
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:312: in execute
    self.error_handler.check_response(response)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py:242: in check_response
    raise exception_class(message, screen, stacktrace)
E   selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
/usr/local/lib/python3.6/dist-packages/selene/elements.py:188: in _wait_with_screenshot
    return wait_for(entity, condition, timeout, polling)
/usr/local/lib/python3.6/dist-packages/selene/wait.py:35: in wait_for
    reason=reason_string), screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
t/test_front_page_search.py:58: in test_search_2
    .should(be.visible)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:306: in should
    _wait_with_screenshot(self._webdriver, self, condition, timeout)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:193: in _wait_with_screenshot
    raise TimeoutException(msg, e.screen, e.stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats
E               screenshot: file:///opt/work/screen_1592082017310.png
------------------------------- pytest-selenium --------------------------------
URL: https://www.google.com/search?source=hp&ei=fD7lXpLUOZr5tAbOsYjwAQ&q=cheese&oq=cheese&gs_lcp=CgZwc3ktYWIQDDIFCAAQsQMyBQgAELEDMgUIABCxAzIFCAAQsQMyAggAMgIIADICCAAyBQgAELEDMgIIADIFCAAQsQNQvAZYngdgzghoAHAAeACAAWuIAWuSAQMwLjGYAQCgAQGqAQdnd3Mtd2l6&sclient=psy-ab&ved=0ahUKEwiSgvjl1__pAhWaPM0KHc4YAh4Q4dUDCAg
______________________ TestFrontPageSearch.test_search_3 _______________________
/usr/local/lib/python3.6/dist-packages/selene/wait.py:13: in wait_for
    return condition.fn(entity)
/usr/local/lib/python3.6/dist-packages/selene/conditions.py:141: in fn
    return self.match(element.get_actual_webelement())
/usr/local/lib/python3.6/dist-packages/selene/elements.py:205: in get_actual_webelement
    return self.__delegate__
/usr/local/lib/python3.6/dist-packages/selene/elements.py:200: in __delegate__
    return self._locator.find()
/usr/local/lib/python3.6/dist-packages/selene/elements.py:45: in find
    return self._search_context.find_element(*self._by)
/usr/local/lib/python3.6/dist-packages/selene/driver.py:89: in find_element
    return self._webdriver.find_element(by, value)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:955: in find_element
    'value': value})['value']
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:312: in execute
    self.error_handler.check_response(response)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py:242: in check_response
    raise exception_class(message, screen, stacktrace)
E   selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
/usr/local/lib/python3.6/dist-packages/selene/elements.py:188: in _wait_with_screenshot
    return wait_for(entity, condition, timeout, polling)
/usr/local/lib/python3.6/dist-packages/selene/wait.py:35: in wait_for
    reason=reason_string), screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
t/test_front_page_search.py:72: in test_search_3
    .result_stats.should(be.visible)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:306: in should
    _wait_with_screenshot(self._webdriver, self, condition, timeout)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:193: in _wait_with_screenshot
    raise TimeoutException(msg, e.screen, e.stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats
E               screenshot: file:///opt/work/screen_1592082017311.png
------------------------------- pytest-selenium --------------------------------
URL: https://www.google.com/search?source=hp&ei=kD7lXqUKzqy1Bp-Im4gC&q=cheese&oq=cheese&gs_lcp=CgZwc3ktYWIQDDIFCAAQsQMyBQgAELEDMgUIABCxAzIFCAAQsQMyAggAMgIIADICCAAyBQgAELEDMgUIABCxAzIFCAAQsQM6BQgAEIMBUIwCWMsCYIMFaABwAHgCgAGYAogBxwaSAQUwLjEuM5gBAKABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwilkoPv1__pAhVOVs0KHR_EBiEQ4dUDCAg
______________________ TestFrontPageSearch.test_search_4 _______________________
/usr/local/lib/python3.6/dist-packages/selene/wait.py:13: in wait_for
    return condition.fn(entity)
/usr/local/lib/python3.6/dist-packages/selene/conditions.py:141: in fn
    return self.match(element.get_actual_webelement())
/usr/local/lib/python3.6/dist-packages/selene/elements.py:205: in get_actual_webelement
    return self.__delegate__
/usr/local/lib/python3.6/dist-packages/selene/elements.py:200: in __delegate__
    return self._locator.find()
/usr/local/lib/python3.6/dist-packages/selene/elements.py:45: in find
    return self._search_context.find_element(*self._by)
/usr/local/lib/python3.6/dist-packages/selene/driver.py:89: in find_element
    return self._webdriver.find_element(by, value)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:955: in find_element
    'value': value})['value']
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py:312: in execute
    self.error_handler.check_response(response)
/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py:242: in check_response
    raise exception_class(message, screen, stacktrace)
E   selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
/usr/local/lib/python3.6/dist-packages/selene/elements.py:188: in _wait_with_screenshot
    return wait_for(entity, condition, timeout, polling)
/usr/local/lib/python3.6/dist-packages/selene/wait.py:35: in wait_for
    reason=reason_string), screen, stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats

During handling of the above exception, another exception occurred:
t/test_front_page_search.py:86: in test_search_4
    .result_stats.should(be.visible)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:306: in should
    _wait_with_screenshot(self._webdriver, self, condition, timeout)
/usr/local/lib/python3.6/dist-packages/selene/elements.py:193: in _wait_with_screenshot
    raise TimeoutException(msg, e.screen, e.stacktrace)
E   selenium.common.exceptions.TimeoutException: Message: 
E               failed while waiting 4 seconds
E               to assert Visible
E               for first_by('css selector', '#resultStats')
E   
E               reason: NoSuchElementException: Unable to locate element: #resultStats
E               screenshot: file:///opt/work/screen_1592082017312.png
------------------------------- pytest-selenium --------------------------------
URL: https://www.google.com/search?source=hp&ei=oj7lXs-MGtWE9PwPl5u2mAs&q=cheese&oq=cheese&gs_lcp=CgZwc3ktYWIQDDIFCAAQsQMyBQgAELEDMgUIABCxAzIFCAAQsQMyAggAMgIIADICCAAyBQgAELEDMgUIABCxAzIFCAAQsQM6BQgAEIMBUKYEWKMFYO8GaABwAHgBgAG_AYgB8gSSAQMwLjSYAQCgAQGqAQdnd3Mtd2l6&sclient=psy-ab&ved=0ahUKEwjP5ef31__pAhVVAp0JHZeNDbMQ4dUDCAg
------------------- generated xml file: /opt/work/result.xml -------------------
=================== 4 failed, 5 deselected in 74.69 seconds ====================
make: *** [test] Error 1
NETWORK=templatenet_default \
	GRID_TIMEOUT=30000 \
	SELENIUM_VERSION=3.8.1-dubnium \
	docker-compose -f /Users/varindersingh/Dropbox/Mac_Documents/Workspace/seleniumconf2018/template/docker/grid/docker-compose.yml -p templatenet down
Stopping templatenet_firefox_1 ... 
Stopping templatenet_chrome_1  ... 
Stopping selenium-hub          ... 
[2A[2KStopping templatenet_chrome_1  ... [32mdone[0m[2B[3A[2KStopping templatenet_firefox_1 ... [32mdone[0m[3B[1A[2KStopping selenium-hub          ... [32mdone[0m[1BRemoving templatenet_firefox_1 ... 
Removing templatenet_chrome_1  ... 
Removing selenium-hub          ... 
[1A[2KRemoving selenium-hub          ... [32mdone[0m[1B[2A[2KRemoving templatenet_chrome_1  ... [32mdone[0m[2B[3A[2KRemoving templatenet_firefox_1 ... [32mdone[0m[3BNetwork templatenet_default is external, skipping
Removing network: templatenet_default
templatenet_default
